dist: trusty
sudo: require

os: linux
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - boost1.70

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --version
  - cmake .
  - cmake  --build . -- -j2