dist: trusty
sudo: require

os: linux
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - boost1.67

script:
  - cmake -S . -B ./build -D ENABLE_COVERAGE:BOOL=ON ../
  - cmake --build ./build -- -j2
  - cd build && ctest -j2