dist: trusty
sudo: false
language: cpp

before_install:
  - sudo add-apt-repository ppa:mhier/libboost-latest
  - sudo apt-get install libssl-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2



