dist: trusty
sudo: false
language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get dist-upgrade
  - sudo apt-get install libboost1X.71-all-dev
  - sudo apt-get install libssl-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2



